apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backimage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backimage
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50